version: '3.9'

services:

  hyperf-skeleton:
    container_name: hyperf-skeleton
    build:
        context: ./
    working_dir: /app
    entrypoint: ["php", "bin/hyperf.php", "server:watch"]
    volumes:
      - ./:/app
    links:
        - mongo-poc
        - redis-poc
    ports:
      - 9501:9501
    networks:
      - network-poc
      
networks:
  network-poc:
    external: true